# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redis-ui}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jwelshiv"]
  s.date = %q{2011-05-23}
  s.default_executable = %q{redis-ui}
  s.description = %q{RedisUI is a redis db web accessible viewer}
  s.email = %q{james@supermatter.com}
  s.executables = ["redis-ui"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/redis-ui",
    "config.ru",
    "lib/redis-ui.rb",
    "lib/static/js/.DS_Store",
    "lib/static/js/app/app.js",
    "lib/static/js/app/models.js",
    "lib/static/js/lib/backbone.js",
    "lib/static/js/lib/underscore.js",
    "lib/static/stylesheets/redis-ui.css",
    "lib/views/index.html.erb",
    "lib/views/layout.html.erb",
    "lib/views/show.html.erb",
    "pkg/redis-ui-0.1.0.gem",
    "pkg/redis-ui-0.1.1.gem",
    "redis-ui.gemspec",
    "test/helper.rb",
    "test/test_redis_ui.rb"
  ]
  s.homepage = %q{http://github.com/jwelshiv/redis-ui}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Sinatra backed redis ui}
  s.test_files = [
    "test/helper.rb",
    "test/test_redis_ui.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 1"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 1"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

